### ISSUE TITLE
Can you add local full-text search？

### ISSUE THREAD

**Issue by Briy09** [abhn/abhn.github.io#3]
Awesome theme！
Can you integrate local search？
refer：
https://simpleyyt.com/jekyll-theme-next/  , search “is” for example.
https://github.com/simpleyyt/jekyll-theme-next

**Comment by abhn** [comment]
Thank you for dropping by. Including content search was my plan all along, but Algolia seems to be restricting record sizes to 10kb each, which many of my posts exceed. 

A possible solution is to generate a json file and use something like netlify lambda functions (and host the blog on netlify). 

Don't have time for that at the moment. If you have a simpler solution, please let me know and I can think of integrating it. :-)
